openapi: 3.0.3
info:
  title: Flexgrid Flex Offer API
  description: "Interface for aggregating multiple Flex Offers into a single\naggregated\
    \ offer.\n\nThe credentials for the API are from the central DB can be obtained\n\
    by the ICCS team of the [FlexGrid project](https://flexgrid-project.eu)\n\nUse\
    \ the central DB api defined at\n[https://db.flexgrid-project.eu/swagger/](https://db.flexgrid-project.eu/swagger/)\n\
    for obtaining the objects for the requests (dr_prosumers, flex_request)"
  contact:
    name: Dimitros J. Vergados
    url: https://flexgrid-project.eu
  license:
    name: GNU
  version: 1.0.1
servers:
- url: https://flexoffers.flexgrid-project.eu/
security:
- oAuth2:
  - post_flex_offers
paths:
  /flex-offers:
    post:
      tags:
      - Flex Offers (UCS 4.3)
      summary: Aggragates several Flex offers into a single offer
      description: "This endpoint is for aggregating flex offers\n\nThe `flex_offers`\
        \ field contains the `name` fields of the `flex_offers` that will be aggregated.\n\
        To obtain the names use the central DB api defined here: [https://db.flexgrid-project.eu/swagger/#/Dr_prosumer/getflex_offers](https://db.flexgrid-project.eu/swagger/#/Dr_prosumer/getflex_offers)\n\
        \nThe `flex_request` field contains the `name` field of the `flex_request`\
        \ that will be used for calculating the resulting revenues and quantities.\n\
        To obtain the name use the central DB api defined here: [https://db.flexgrid-project.eu/swagger/#/Flex_request/getflex_requests](hhttps://db.flexgrid-project.eu/swagger/#/Flex_request/getflex_requests)\n\
        \nIt returns the an aggregated offer, and the expected cleance quantities\
        \ and prices \n"
      operationId: flex_offers_post
      requestBody:
        $ref: '#/components/requestBodies/FlexOfferParams'
      responses:
        "201":
          description: operation has been successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FlexOfferResult'
        "400":
          description: bad request
      security:
      - oAuth2: []
      x-openapi-router-controller: swagger_server.controllers.flex_offers_ucs43_controller
components:
  schemas:
    FlexOfferParams:
      required:
      - end_datetime
      - flex_offers
      - flex_request
      - start_datetime
      type: object
      properties:
        start_datetime:
          type: string
          format: date-time
          example: 2021-11-11T00:00:00Z
        end_datetime:
          type: string
          format: date-time
          example: 2021-11-12T00:00:00Z
        flex_offers:
          minItems: 1
          type: array
          example:
          - flex_offer_0
          - flex_offer_0
          items:
            type: string
        flex_request:
          type: string
          example: flex_request_1_Low_Large
    FlexOfferResult:
      type: object
      properties:
        aggr_flex_offer:
          $ref: '#/components/schemas/FlexOfferResult_aggr_flex_offer'
        expected_result:
          type: array
          items:
            $ref: '#/components/schemas/FlexOfferResult_expected_result'
      example:
        aggr_flex_offer:
          country: country
          data_points:
          - flexibility:
            - minquantity: 1.4658129805029452
              price_euro_per_kw: 0.8008281904610115
              quantity_kw: 6.027456183070403
              direction: direction
            - minquantity: 1.4658129805029452
              price_euro_per_kw: 0.8008281904610115
              quantity_kw: 6.027456183070403
              direction: direction
            timestamp: timestamp
          - flexibility:
            - minquantity: 1.4658129805029452
              price_euro_per_kw: 0.8008281904610115
              quantity_kw: 6.027456183070403
              direction: direction
            - minquantity: 1.4658129805029452
              price_euro_per_kw: 0.8008281904610115
              quantity_kw: 6.027456183070403
              direction: direction
            timestamp: timestamp
          name: name
          location:
            name: name
        expected_result:
        - price_euro_per_kw: 5.637376656633329
          quantity_kw: 5.962133916683182
          timestamp: timestamp
        - price_euro_per_kw: 5.637376656633329
          quantity_kw: 5.962133916683182
          timestamp: timestamp
    FlexOfferDataPoint:
      type: object
      properties:
        timestamp:
          type: string
        flexibility:
          type: array
          items:
            $ref: '#/components/schemas/FlexOfferDataPoint_flexibility'
      example:
        flexibility:
        - minquantity: 1.4658129805029452
          price_euro_per_kw: 0.8008281904610115
          quantity_kw: 6.027456183070403
          direction: direction
        - minquantity: 1.4658129805029452
          price_euro_per_kw: 0.8008281904610115
          quantity_kw: 6.027456183070403
          direction: direction
        timestamp: timestamp
    FlexOfferResult_aggr_flex_offer_location:
      type: object
      properties:
        name:
          type: string
      example:
        name: name
    FlexOfferResult_aggr_flex_offer:
      type: object
      properties:
        name:
          type: string
        country:
          type: string
        location:
          $ref: '#/components/schemas/FlexOfferResult_aggr_flex_offer_location'
        data_points:
          type: array
          items:
            $ref: '#/components/schemas/FlexOfferDataPoint'
      example:
        country: country
        data_points:
        - flexibility:
          - minquantity: 1.4658129805029452
            price_euro_per_kw: 0.8008281904610115
            quantity_kw: 6.027456183070403
            direction: direction
          - minquantity: 1.4658129805029452
            price_euro_per_kw: 0.8008281904610115
            quantity_kw: 6.027456183070403
            direction: direction
          timestamp: timestamp
        - flexibility:
          - minquantity: 1.4658129805029452
            price_euro_per_kw: 0.8008281904610115
            quantity_kw: 6.027456183070403
            direction: direction
          - minquantity: 1.4658129805029452
            price_euro_per_kw: 0.8008281904610115
            quantity_kw: 6.027456183070403
            direction: direction
          timestamp: timestamp
        name: name
        location:
          name: name
    FlexOfferResult_expected_result:
      type: object
      properties:
        timestamp:
          type: string
        quantity_kw:
          type: number
        price_euro_per_kw:
          type: number
      example:
        price_euro_per_kw: 5.637376656633329
        quantity_kw: 5.962133916683182
        timestamp: timestamp
    FlexOfferDataPoint_flexibility:
      type: object
      properties:
        price_euro_per_kw:
          type: number
        quantity_kw:
          type: number
        direction:
          type: string
        minquantity:
          type: number
      example:
        minquantity: 1.4658129805029452
        price_euro_per_kw: 0.8008281904610115
        quantity_kw: 6.027456183070403
        direction: direction
  requestBodies:
    FlexOfferParams:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/FlexOfferParams'
  securitySchemes:
    oAuth2:
      type: oauth2
      description: oAuth2 password credentials.
      flows:
        password:
          tokenUrl: https://db.flexgrid-project.eu/oauth/token
          scopes:
            post_flex_offers: post a flex offer scenario
      x-tokenInfoFunc: swagger_server.controllers.authorization_controller.check_oAuth2
      x-scopeValidateFunc: swagger_server.controllers.authorization_controller.validate_scope_oAuth2

